run:
  timeout: 5m

linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
    - gocyclo
    - goconst
    - revive
